# diffusion_policy_3d/config/task/my_task.yaml

name: isaac_grasping

dataset:
  _target_: diffusion_policy_3d.dataset.my_dataset.IsaacZarrDataset
  zarr_path: data/positive.zarr  # Dataset path
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null


env_runner:
  _target_: diffusion_policy_3d.env_runner.my_env_runner.DummyRunner


shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dim
  action:
    shape: [7]


