robot_path: "/World/ur10e_robotiq2f_140_ROS/ur10e_robotiq2f_140"
tool0_path: "/World/ur10e_robotiq2f_140_ROS/ur10e_robotiq2f_140/ur10e/tool0"
baselink_path: "/World/ur10e_robotiq2f_140_ROS/ur10e_robotiq2f_140/ur10e/base_link"
robotiqpad_R_path: "/World/ur10e_robotiq2f_140_ROS/ur10e_robotiq2f_140/Robotiq_2F_140_config/right_inner_finger"

camera_paths:
  sensor: "/World/ur10e_robotiq2f_140_ROS/ur10e_robotiq2f_140/ur10e/tool0/Camera"
  in_hand: "/World/ur10e_robotiq2f_140_ROS/ur10e_robotiq2f_140/ur10e/tool0/in_hand"
  up: "/World/up"
  front: "/World/front"

obj_prim_paths:
  - path: "/nvidia_cube"
    enabled: false
  - path: "/SM_Mug_A2"
    enabled: false
  - path: "/_11_banana"
    enabled: false
  - path: "/_35_power_drill"
    enabled: false
  - path: "/multi_color_cube_instanceable"
    enabled: true

