# robot_description:
#   urdf_path: "/home/ani/my_Isaac/ur10e_with_gripper.urdf"
#   base_link: "base_link"
#   end_effector_link: "tool0"

# cspace:
#   coordinates:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   position_limits:
#     shoulder_pan_joint: [-3.14, 3.14]
#     shoulder_lift_joint: [-3.14, 3.14]
#     elbow_joint: [-3.14, 3.14]
#     wrist_1_joint: [-3.14, 3.14]
#     wrist_2_joint: [-3.14, 3.14]
#     wrist_3_joint: [-3.14, 3.14]
#   velocity_limits:
#     shoulder_pan_joint: 1.0
#     shoulder_lift_joint: 1.0
#     elbow_joint: 1.0
#     wrist_1_joint: 1.0
#     wrist_2_joint: 1.0
#     wrist_3_joint: 1.0
#   acceleration_limits:
#     shoulder_pan_joint: 5.0
#     shoulder_lift_joint: 5.0
#     elbow_joint: 5.0
#     wrist_1_joint: 5.0
#     wrist_2_joint: 5.0
#     wrist_3_joint: 5.0

# # RRT Parameters
# seed: 42
# step_size: 0.05
# max_iterations: 5000
# goal_bias: 0.1
# max_planning_time: 20.0
# max_sampling: 10000
# distance_metric_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
# task_space_frame_name: "tool0"
# task_space_limits:
#   - [0.2, 1.2]   # X
#   - [-0.8, 0.8]  # Y
#   - [0.0, 1.0]   # Z
  
# task_space_planning_params:
#   max_iterations: 500
#   step_size: 0.05
#   goal_bias: 0.1
#   #exploration_fraction: 0.2
#   collision_check_resolution: 0.01
#   translation_target_zone_tolerance: 0.01
#   orientation_target_zone_tolerance: 0.01
#   translation_target_final_tolerance: 0.001
#   orientation_target_final_tolerance: 0.001
#   translation_gradient_weight: 1.0  
#   orientation_gradient_weight: 1.0
#   nn_translation_distance_weight: 1.0
#   nn_orientation_distance_weight: 1.0
#   task_space_exploitation_fraction: 0.5
#   task_space_exploration_fraction: 0.5
#   max_extension_substeps_away_from_target: 20
#   max_extension_substeps_near_target: 10
#   extension_substep_target_region_scale_factor: 1.0
#   unexploited_nodes_culling_scalar: 0.1
#   gradient_substep_size: 0.01
#   path_smoothness_weight: 0.1       #
#   goal_reach_tolerance: 0.01        #

# c_space_planning_params:
#   max_iterations: 1000
#   step_size: 0.05
#   goal_bias: 0.1
#   exploration_fraction: 0.2
#   collision_check_resolution: 0.01
#   collision_avoidance_weight: 10.0  #


# replanning_enabled: false


# # # Collision
# # collision:
# #   enabled: true
# #   collision_spheres: "/home/ani/my_Isaac/collision_spheres.yaml"
# #   self_collision: true
# #   environment_collision: true


seed: 42
step_size: 0.05
max_iterations: 50000
max_sampling: 10000
distance_metric_weights: [3.0, 2.0, 2.0, 1.5, 1.5, 1.0]
task_space_frame_name: "tool0"
task_space_limits: [[0, 1.35], [-1.35, 1.35], [0.0, 2.0]]
cuda_tree_params:
  max_num_nodes: 10000
  max_buffer_size: 30
  num_nodes_cpu_gpu_crossover: 3000
c_space_planning_params:
  exploration_fraction: 0.5
task_space_planning_params:
  translation_target_zone_tolerance: 0.05
  orientation_target_zone_tolerance: 0.09
  translation_target_final_tolerance: 1e-4
  orientation_target_final_tolerance: 0.005
  translation_gradient_weight: 1.0
  orientation_gradient_weight: 0.125
  nn_translation_distance_weight: 1.0
  nn_orientation_distance_weight: 0.125
  task_space_exploitation_fraction: 0.4
  task_space_exploration_fraction: 0.1
  max_extension_substeps_away_from_target: 6
  max_extension_substeps_near_target: 50
  extension_substep_target_region_scale_factor: 2.0
  unexploited_nodes_culling_scalar: 1.0
  gradient_substep_size: 0.025
